<link rel="stylesheet" href="<?= base_url() ?>/assets/css/style.css">
<link rel="stylesheet" href="<?= base_url() ?>/assets/vendors/toastr/toastr.min.css">
<link rel="stylesheet" href="<?= base_url() ?>/assets/vendors/tempusdominus/css/tempusdominus-bootstrap-4.min.css">
<link rel="stylesheet" href="<?= base_url() ?>/assets/vendors/summernote/summernote-bs4.min.css">
<link rel="stylesheet" href="<?= base_url() ?>/assets/vendors/select2/css/select2.min.css">
<link rel="stylesheet" href="<?= base_url() ?>/assets/vendors/select2/css/select2-bootstrap-5-theme.min.css">
<link rel="stylesheet" href="<?= base_url() ?>/assets/vendors/datatables/datatables.min.css">
<link rel="stylesheet" href="<?= base_url() ?>/assets/vendors/datatables/responsive/css/responsive.bootstrap5.min.css">
<link rel="stylesheet" href="<?= base_url() ?>/assets/vendors/datatables/theme/css/dataTables.bootstrap5.min.css">
<link rel="stylesheet" href="<?= base_url() ?>/assets/vendors/bootstrap-toggle/css/bootstrap2-toggle.min.css">
<link rel="stylesheet" href="<?= base_url() ?>/assets/vendors/bootstrap-switch/css/bootstrap3/bootstrap-switch.min.css">
<link rel="stylesheet" href="<?= base_url() ?>/css/main.css">
